<?php $orderId = Mage::getSingleton('checkout/session')->getLastOrderId(); ?>
<?php if($orderId): ?>
    <?php $order = Mage::getModel('sales/order')->load($orderId); ?>
    <div data-findify-event="purchase" data-findify-order-id="<?php echo $order->getIncrementId(); ?>" data-findify-currency="<?php echo $order->getOrderCurrencyCode(); ?>" data-findify-revenue="<?php echo $order->getGrandTotal(); ?>" style="display:none;">
        <?php 
        $prodarr=array();
        $i=0;
        foreach($order->getAllItems() AS $item) :
            $pro=Mage::getModel('catalog/product')->load($item->getProductId());
            if($pro->getTypeId() == "simple"){
                $parentIds = Mage::getModel('catalog/product_type_grouped')->getParentIdsByChild($pro->getId());
                if(!$parentIds)
                    $parentIds = Mage::getModel('catalog/product_type_configurable')->getParentIdsByChild($pro->getId());
                if(isset($parentIds[0])){
                    $parent = Mage::getModel('catalog/product')->load($parentIds[0]);
                    $prid = $parent->getId();
                } else $prid = $pro->getId();
            } else $prid = $item->getProductId();
            $prodarr[$i]['id']=$prid;
            $prodarr[$i]['type']=$pro->getTypeId();
            $prodarr[$i]['price']=$item->getPrice();
            if($pro->getTypeId() != "configurable"){
                if($item->getPrice()==0 && $prid==$prodarr[$i-1]['id'] && $prodarr[$i-1]['type']=="configurable") $pric=$prodarr[$i-1]['price'];
                else  $pric=$item->getPrice();
	        ?>
		<div data-findify-item-id="<?php echo $prid; ?>" data-findify-variant-item-id="<?php echo $prid; ?>" data-findify-unit-price="<?php echo $pric; ?>" data-findify-quantity="<?php echo $item->getQtyOrdered(); ?>"></div>
                <?php
            }
            $i++;
        endforeach; ?>
    </div>
<?php endif; ?>
